### ISSUE TITLE
RuntimeError: espeak not installed on your system

### ISSUE THREAD

**Issue by JocelynVelarde** [dscripka/synthetic_speech_dataset_generation#1]
Hello @dscripka I’m encountering this error when trying to run the following command as specified on the README

```bash
python generate_clips.py --model VITS --text "This is some test speech" --N 1 --output_dir generated_clips
```

I already tried installing espeak with Homebrew, and I ran a test script and it seems to be working well.  Not very sure on why it is not working when I run the `generate_clips.py` script

```
(3.8.20) jvelarde@MAC-G9HFG2NFV4 synthetic_speech_dataset_generation % python generate_clips.py --model VITS --text "This is some test speech" --N 1 --output_dir generated_clips
Traceback (most recent call last):
  File "generate_clips.py", line 114, in <module>
    from data_utils import TextAudioLoader, TextAudioCollate, TextAudioSpeakerLoader, TextAudioSpeakerCollate
  File "/Users/jvelarde/Desktop/synthetic_speech_dataset_generation/models/vits/data_utils.py", line 11, in <module>
    from text import text_to_sequence, cleaned_text_to_sequence
  File "/Users/jvelarde/Desktop/synthetic_speech_dataset_generation/models/vits/text/__init__.py", line 2, in <module>
    from text import cleaners
  File "/Users/jvelarde/Desktop/synthetic_speech_dataset_generation/models/vits/text/cleaners.py", line 48, in <module>
    espeak_backend = EspeakBackend('en-us', preserve_punctuation=True, with_stress=True)
  File "/Users/jvelarde/.pyenv/versions/3.8.20/lib/python3.8/site-packages/phonemizer/backend/espeak/espeak.py", line 45, in __init__
    super().__init__(
  File "/Users/jvelarde/.pyenv/versions/3.8.20/lib/python3.8/site-packages/phonemizer/backend/espeak/base.py", line 39, in __init__
    super().__init__(
  File "/Users/jvelarde/.pyenv/versions/3.8.20/lib/python3.8/site-packages/phonemizer/backend/base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system
```

**Comment by sangheonEN** [comment]
sudo apt update
sudo apt install espeak

**Comment by JocelynVelarde** [comment]
i tried that, still no success :(
i will start with a clean copy of the repo, perhaps i messed something up while installing things

**Comment by UmairDL** [comment]
i was able to fix this espeak issue, by firstly downloading .msi file from espeak repo (https://github.com/espeak-ng/espeak-ng/releases) and then after installation just copy that installed espeak folder into your current libraries environment in my case it was copy C:\Program Files\eSpeak NG and paste into  C:\Users\YOUR SYSTEM NAME\PycharmProjects\project\.venv\Lib\site-packages
